osx_image: xcode12
language: objective-c
before_install:
- openssl aes-256-cbc -K $encrypted_6c55ef9b434a_key -iv $encrypted_6c55ef9b434a_iv
  -in grades_private_key.txt.enc -out grades_private_key.txt -d
- brew install git-secret swiftlint swiftgen swiftformat || true
- gem install xcpretty-travis-formatter
before_script:
- gpg --batch --import grades_private_key.txt
- git secret reveal -p "$GIT_SECRET_PASSPHRASE"
script:
- set -o pipefail
- xcodebuild test -project Grades.xcodeproj -scheme Debug -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.0' | xcpretty --test -f `xcpretty-travis-formatter`
