osx_image: xcode11
language: objective-c
cache:
  directories:
  - Carthage
before_install:
- openssl aes-256-cbc -K $encrypted_6c55ef9b434a_key -iv $encrypted_6c55ef9b434a_iv
  -in grades_private_key.txt.enc -out grades_private_key.txt -d
- brew install git-secret carthage swiftlint swiftgen swiftformat || true
- gem install xcpretty-travis-formatter
install:
- carthage bootstrap --new-resolver --platform iOS --no-use-binaries --cache-builds
before_script:
- gpg --batch --import grades_private_key.txt
- git secret reveal -p "$GIT_SECRET_PASSPHRASE"
script:
- set -o pipefail
- xcodebuild clean test -project Grades.xcodeproj -scheme Debug -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.0' | xcpretty --test -f `xcpretty-travis-formatter`
after_failure:
  - cat $TMPDIR/carthage-*.log
