osx_image: xcode10.2
language: objective-c
cache:
  directories:
    - Carthage

before_install:
  - brew update
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
  - gem install xcpretty-travis-formatter

before_script:
  - carthage bootstrap --platform iOS --no-use-binaries --cache-builds

install:
  - carthage update --cache-builds
script:
  - set -o pipefail
  - xcodebuild clean test -project Grades -scheme Debug -destination 'platform=iOS Simulator,name=iPhone Xs,OS=12.2' | xcpretty -f `xcpretty-travis-formatter`