osx_image: xcode10.2
language: objective-c
cache:
  directories:
  - Carthage
before_install:
- openssl aes-256-cbc -K $encrypted_6c55ef9b434a_key -iv $encrypted_6c55ef9b434a_iv
  -in grades_private_key.txt.enc -out grades_private_key.txt -d
install:
- bundle install
before_script:
- gpg --batch --import grades_private_key.txt
- git secret reveal -p "$GIT_SECRET_PASSPHRASE"
script:
  - fastlane test